### ISSUE TITLE
-begin and -end are ignored

### ISSUE THREAD

**Issue by Twilight-Logic** [Arakula/f9dasm#22] opened 2022-10-06 07:34 UTC
I am trying to de-comple a section of code in a file containing code for the 6800. I compiled  f9dasm on Linux Mint 20.3. Compilation completed with some warnings but no errors.

Since the 6800 code would normally get loaded at address 8000 hex, along with `-begin` and `-end` I used the `-offset` parameter something like:

`./f9dasm -begin 003E -end 0151 -offset 8000 -6800 bpl.bin
`

While the `-offset` parameter works and addresses in the output are shown as starting from 8000, disassembly always seems to start at the beginning of the file, rather than at the specified beginning offset 003E. The readme says to specify the beginning and end offsets as hex, so I used hex bytes. For example I tried both 3E and 151 as well as 003E and 0151 for consistency. I also tried 803E.

```
     ORG     $8000

        NEGA                             ;8000: 40             '@'
        FCB     $51                      ;8001: 51             'Q'
        FCB     $00                      ;8002: 00             '.'
        FCB     $00                      ;8003: 00             '.'
        FCB     $00                      ;8004: 00             '.'
        FCB     $00                      ;8005: 00             '.'
		etc
```

In the output above, 8000 corresponds to address 0. I was expecting de-compilation to start at 803E. I was expecting the de-compilation to run up to address 8151. It ran up to the end of the file.

If I omit `-offset 8000` then the ORG is 0 and the listing starts at address 0000 instead of 8000, but not at offset 003E as expected.

When `begin` and `end` are used in an info file, the `end` parameter seems to get interpreted as the `offset` parameter. This is my info file:

```
file bpl.bin
option offset 8000
option begin 003E
option end 0151
option 6800
```
Here is the command I used:

`./f9dasm -info test.info`

De-compilation begins at the the start of the file and not at the requested offset and runs through the entire file but the start address in the output is shown as address 0151. 

```
 ORG     $0151

        NEGA                             ;0151: 40             '@'
        FCB     $51                      ;0152: 51             'Q'
        FCB     $00                      ;0153: 00             '.'
        FCB     $00                      ;0154: 00             '.'
        FCB     $00                      ;0155: 00             '.'
        FCB     $00                      ;0156: 00             '.'
		etc
```

Again, in the output above, I am expecting the start address of the code to be 8000 and the de-compilation to start at 803E. I was expecting the de-compilation to run up to address 8151. It ran up to the end of the file.

**Comment by Arakula** [comment] 2022-10-06 08:31
> Since the 6800 code would normally get loaded at address 8000 hex, along with '-begin' and '-end' I used the '-offset' parameter something like:
> 
> `./f9dasm -begin 003E -end 0151 -offset 8000 -6800 bpl.bin `

I think `./f9dasm -begin 803E -end 8151 -offset 8000 -6800 bpl.bin` would work better. `offset`is the most important of these 3 options, especially for binary files, since it determines where in the address space the binary is loaded. `begin` and `end ` then can be used to refine which part of that area should be disassembled. `begin`and `end`are auto-adjusted if they are set to something outside the area in the address space where the binary is loaded.

In your info file, set `offset` before specifying ` file`. `begin`and `end`can be specified later, but should be set to 803e / 8151.

**Comment by Twilight-Logic** [comment] 2022-10-06 08:53
Thank you for your very quick reply!

I tried -begin 803E and -end 8151 as you suggested, but unfortunately the de-compile still starts at 8000 and de-compiles the whole file. I even tried changing the order of the parameters on the command line:

` ./f9dasm -offset 8000 -begin 803E -end 8151 -6800 bpl.bin
`
This stilkl starts at offset 0 and the de-compile runs to the end of the file.

Following your instructions, I also changed the info file to this:

```
option offset 8000
file bpl.bin
option begin 803E
option end 8151
option 6800
```

I still get the same result. I even tried moving `file bpl.bin` to the end so that its after `begin` and `end` but it made no difference. This still starts the addressing at 8151 but begins at offset 0 and de-compiles to the end of the file.

**Comment by Arakula** [comment] 2022-10-06 12:35
I'll look into it, then.
Hmmm ... looks like the following code piece in loadfile() doesn't work as it should:
```
  if (offset < *pbegin)                 /* set begin if not specified        */
    *pbegin = offset;
  if (*pend < offset + off - 1)         /* set end if not specified          */
    *pend = offset + off -1;
```
I'll think about it. That should guard against invalid settings (like "load 256 bytes at offset 8000 but begin defaults to FFFF, so reset begin to 8000", for eample) ... but obviously it does a bit more than intended. This would work ONLY if begin and end are left at their default values (begin FFFF, end 0).

**Comment by Twilight-Logic** [comment] 2022-10-06 18:41
Thank you. I didn't get a chance to have a look at the f9dasm program code earlier but just had a quick scan through it now. I am curious as to why the default values for begin=FFFF and end=0? Given that is the case, provided that a value of `offset > FFFF` has not been erroneously specified on the command line, `offset` will always be smaller than `*pbegin` and therefore `*pbegin` will always be set equal to `offset`, which explains why it always starts at the default start point. In a similar vein, `end` should always be smaller then `offset + off` (`off` being set to the file length) so `*pend` always gets set to the end of the file.

Please let me know what you come up with. I will have a think as well.

One thing that springs to mind is that maybe there should also be guard against `end` > `begin` which displays the usage in the event or some error message to explain? I know its obvious and shouldn't happen....

**Comment by Arakula** [comment] 2022-10-06 19:03
Defaults of begin=FFFF and end=0 practically guarantee that the values are corrected to the "real" boundaries.
If you're feeling adventurous, I'm attaching my current code for you to try here - seems to work much better, but I have only tested it in a very cursory way.
[f9dasm.zip](https://github.com/Arakula/f9dasm/files/9727809/f9dasm.zip)
Might break if you load something at offset 0 and don't set end manually; I still got to try that.
[Edit:] yep, breaks. So please consider the code in the .zip file as a quick fix for your particular problem, but not as a generally working solution. I'll refine it tomorrow (not much to do ... in theory, initializing end to 0x10000 instead of 0 should be sufficient).

**Comment by Arakula** [comment] 2022-10-06 19:39
> One thing that springs to mind is that maybe there should also be guard against `end` > `begin` which displays the usage in the event or some error message to explain?

I'm a big fan of the GIGO principle ... if you willingly enter nonsensical constraints, you should get what you deserve 😎

**Comment by Arakula** [comment] 2022-10-07 06:19
OK, I've uploaded V1.81. This should improve begin & end handling a lot ... and also reduce gcc's output with -Wall to a non-issue I can't "fix", since it's fully intentional and commented.

I'm closing this issue now; if you come across further problems with begin/end/offset, feel free to re-open it.

**Comment by Twilight-Logic** [comment] 2022-10-07 08:50
I take your point about GIGO!

Thank you for a very quick response and fix. Command line now works as expected. Running it from an info file still misbehaves though. I used this info config:

```
option offset 8000
option begin 803E
option end 8151
option 6800
file bpl.bin

```

This was the output:

$ ./f9dasm -info bsave.info
f9dasm: M6800/1/2/3/8/9 / H6309 Binary/OS9/FLEX9 Disassembler V1.81
Loaded binary file bpl.bin

```
;****************************************************
;* Used Labels                                      *
;****************************************************


;****************************************************
;* Program Code / Data Areas                        *
;****************************************************

        ORG     $8151

        NEGA                             ;8151: 40             '@'

        END
```
I do appreciate the command line fix though. Thank you.

**Comment by Arakula** [comment] 2022-10-07 09:26
OK, quick fix for this special case ... change
```
option offset 8000
option begin 803E
option end 8151
option 6800
file bpl.bin
```
to
```
option begin 803E
option end 8151
option 6800
file bpl.bin 8000
```
(with or without the `option offset 8000` line; that becomes irrelevant).

Unfortunately, this one shows a little conceptual problem with `begin`/`end` together with `file` which requires additional changes ... and some thought. In any case, the issue is definitely not completely fixed, so I'm reopening this.

**Comment by Arakula** [comment] 2022-10-07 10:00
This will need a little code fix plus an addition to the documentation, I think.
Because it's a fine little mess ...
the `file` directive can be given with or without an additional address parameter in the info file. If an address is given, the file is loaded at this address (as in my changes to your info file above). If it's given _without_ an address, however, f9dasm tries to load it at the address currently given in the `end` variable. Yes, the same one you can set with the `option end` directive.

The reason for that is that this, in theory, should allow f9dasm to load a set of consecutive small binaries (like an array of 2708 EPROM images) simply by specifying them like
```
offset 8000
file 1.bin
file 2.bin
...
file n.bin
```
in the info file; f9dasm would then simply use the previously set `end` variable as the address to load the _n_ th file.

That's the theory. Yesterday's changes to `end` ruined that (as it's initialized to 0x10000 instead of 0 now); plus, it wouldn't have worked correctly anyway, as `end`would be set to the _last_ byte in the previously loaded file, so that byte would be overwritten when a new `file` without address is processed. So, this will need a little code change to get it to work again.

But even then I got a conflict here, as this convenience feature interferes with a manually set `end`address. Resolving this requires one of the following actions:

- change the documentation to highlight the fact that you can't have both `option end` and `file` without load address
- change the file loading code to remember the last used address and use that in consecutive `file` directives instead of the `end`variable.

Of course, changing the documentation would be the easier way, but I'm not convinced it's the _better_ way. I'll think about it.
OK, enough rambling ...

**Comment by Twilight-Logic** [comment] 2022-10-07 11:40
Your suggested modified info file worked fine thanks. Thank you for the detailed explanation. Sorry to have given you a bit of a headache with this one!

I was not aware of this "convenience feature". I did have multiple dump files and just combined them with the `cat` command. Its a great idea though.

It occurred to me that the specified `-end` value could be located in file1 but might also be located in fileN. Since `off` stores the size of the current file, the next file would be loaded at offset + off+1. However, in the case of multiple files, you might need a counter that stores the cumulative value of `off` for each file as it is loaded. The next file would then be loaded at offset + counter + 1. The `-end` value would then serve only the one purpose of indicating the endpoint of the de-compile. Of course, its your project, so its my turn to restrain myself from further rambling...

Thank you for looking into it.

**Comment by Arakula** [comment] 2022-10-07 12:00
> Sorry to have given you a bit of a headache with this one!

Well, the problem was there for many years (since 2008. Yes, really), just waiting to be discovered ...

[f9dasm.zip](https://github.com/Arakula/f9dasm/files/9733677/f9dasm.zip)

Here's a version that _should_ work better, both in command line and info file. It would be great if you could tell me whether it works for you, too.

**Comment by Twilight-Logic** [comment] 2022-10-07 12:58
Thanks. What a quick response again!

Command line still works. Your amended version of the info file works, but unfortunately not my original version with `option offset 8000`. I also tried to combine the original two ROM files using a new info file and unfortunately that doesn't seem to be working either. I have attached my files so you can see exactly what I am doing.

bsave.info - original info file using bpl.bin as source
bsave-alt.info - info file modified as per your advice (works)
combined.info - info file that includes the two original ROM files instead of bpl.bin

[f9dasm-test-01.zip](https://github.com/Arakula/f9dasm/files/9733871/f9dasm-test-01.zip)

**Comment by Arakula** [comment] 2022-10-08 08:05
OK, that was simple ... if option `offset` is set, then I also need to adjust the last load address to `offset`-1.
Here's a new version with just that one additional line; for me, it works with all your 3 info files. Could you please try it?
[f9dasm.zip](https://github.com/Arakula/f9dasm/files/9738732/f9dasm.zip)
If it works for you, too, I'll prepare an official release later today.

**Comment by Twilight-Logic** [comment] 2022-10-08 08:21
Sorry I didn't get a chance to try this yesterday, but I have just tried it this morning and it works with all three of my info file scenarios. In the combined.info file I even set the end address to fall within the second file and this worked as well!

Thank you once again for such a quick response and fix.

**Comment by Arakula** [comment] 2022-10-08 10:22
Phew... OK, I've uploaded https://github.com/Arakula/f9dasm/releases/tag/V1.82 now and close this issue.
Let's see whether it stays closed this time :sunglasses:

**Closed as completed by Arakula** 2022-10-08 10:22 UTC
